name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-go-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build go service image
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/go-service:1.0 \
            ./service/go-service

      - name: Push go service image
        run: |
          docker push $DOCKERHUB_USERNAME/go-service:1.0

  build-node-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Node service
        run: |
          docker build \
            -t $DOCKERHUB_USERNAME/node-service:1.0 \
            ./services/node-service

      - name: Push node service image
        run: |
          docker push $DOCKERHUB_USERNAME/node-service:1.0